train: ../train/images
val: ../valid/images
test: ../test/images

nc: 1
names: ['resistor']

roboflow:
  workspace: resistor-classification-scanner
  project: resistor-scanner
  version: 4
  license: CC BY 4.0
  url: https://universe.roboflow.com/resistor-classification-scanner/resistor-scanner/dataset/4